# Generated by Django 4.0.6 on 2022-11-27 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_list',
            name='isactive',
        ),
    ]
