# Generated by Django 4.0.6 on 2022-11-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_list',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='comments',
        ),
    ]
