# Generated by Django 4.0.6 on 2022-11-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_user_is_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
